version: "3"
services:

  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - postgres-network
    volumes:
      - /dados/postgres:/var/lib/postgresql/data

  pgadmin:
      image: dpage/pgadmin4
      ports:
        - '15432:80'
      environment:
        - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
        - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      networks:
        - postgres-network
      volumes:
        - /dados/pgadmin:/var/lib/pgadmin

networks:
  postgres-network:
    external: true